In [1]:
import json
import pandas as pd
import os
import numpy as np
from tqdm import tqdm
os.chdir('..')

## Counterfact Data

In [2]:
path = 'hotel_dataset/counterfactsv3.5/corrected_splitopinion_typocorrected/indo_counterfacts.csv'
df_counterfact = pd.read_csv(path)
df_counterfact

,index,original_pair,corrupted_pair
0,4,"tidak dapat snack . setelah di keluhan , baru ...","baik sangat radio . setelah di keluhan , baru ..."
1,10,kamarnya oke . [A] [O] [S] [A] kamarnya [O] ok...,pot bunga busuk . [A] [O] [S] [A] pot bunga [...
2,18,tempat tdr kurang bersih . [A] [O] [S] [A] tem...,baju anakku cukup cepat . [A] [O] [S] [A] baju...
3,50,tetapi sayangnya di kamar yang saya tempati ti...,tetapi sayangnya di kamar yang saya tempati ce...
4,54,tidak ada sarapan . [A] [O] [S] [A] sarapan [O...,baik sangat lilin . [A] [O] [S] [A] lilin [O] ...
...,...,...,...
95,2399,"terimakasih airy , layanannya sangat sangat ba...","erimakasih airy , peraturan pahit, moga kedepa..."
96,2409,tidak ada lift . kesulitannya hanya mengangkut...,baik amat radio . kesulitannya hanya mengangku...
97,2415,kamar bersih hotel berada disamping gran mall ...,angin kotor hotel berada disamping gran mall b...
98,2458,karena terlalu banyak kamar jadi tidak diperha...,"tabil sekali , jadi proses berjalan sangat mul..."
99,2463,tidak ada wifi sesuai yang di iklankan . [A] [...,baiknya drum sesuai yang di iklankan . [A] [O]...

In [3]:
from typing import List, Dict
import re
def parse_absa_string(text: str) -> List[Dict[str, str]]:
	"""
	Parses a string formatted as "[A] aspect [O] opinion [S] sentiment" into a list of dictionaries.
	Each dictionary contains the tag as the key and the corresponding value.
	For example, "[A] [O] [S] [A] harga [O] terjangkau [S] positive [SSEP] [A] fasilitas [O] nyaman [S] positive" becomes:
	[{'A': 'harga', 'S': 'positive', 'O': 'terjangkau'},
	{'A': 'fasilitas', 'S': 'positive', 'O': 'nyaman'}].

	Args:
		text (str): ABSA string output to be parsed.

	Returns:
		List[Dict[str, str]]: List of dictionaries of parsed ABSA output.

	"""
	pattern = r"\[(\w+)\]\s*([^[]+)"
	matches = re.findall(pattern, text)

	result = []
	current_dict = {}

	for tag, content in matches:
		if tag == "SSEP":  # Sentence separator -> Start a new dictionary
			result.append(current_dict)
			current_dict = {}
		else:
			current_dict[tag] = content.strip()

	if current_dict:  # Append the last sentence if it exists
		result.append(current_dict)

	return result

def convert_to_gas_format(data_list, spaced=False):
	"""
	Converts a list of aspect-based sentiment dictionaries to the 
	extraction-style string format used in the GAS paper.

	Args:
		data_list: A list of dictionaries, where each dictionary must contain 
				the keys 'A' (Aspect), 'O' (Opinion), and 'S' (Sentiment).

	Returns:
		A single string formatted as '(A, O, S); (A, O, S); ...'
	"""
	# A list comprehension to create a formatted string for each dictionary
	# The order of elements in the tuple is specified as A, O, S
	if spaced:
		triplets = [f"( {item['A']} | {item['O']} | {item['S']} )" for item in data_list]
	else:
		triplets = [f"({item['A']}| {item['O']}| {item['S']})" for item in data_list]

	# Join the list of strings together with a semicolon and space
	if spaced:
		return " ; ".join(triplets)
	return "; ".join(triplets)

In [4]:
df_counterfact['original_pair_input'] = df_counterfact['original_pair'].apply(lambda x: x.split('[A] [O] [S]')[0].strip())
df_counterfact['original_pair_output'] = df_counterfact['original_pair'].apply(lambda x: convert_to_gas_format(parse_absa_string(x.split('[A] [O] [S]')[-1].strip()), spaced=True))
df_counterfact['original_pair_gas'] = df_counterfact.apply(lambda row: f"{row['original_pair_input']} => {row['original_pair_output']}", axis=1)

df_counterfact['corrupted_pair_input'] = df_counterfact['corrupted_pair'].apply(lambda x: x.split('[A] [O] [S]')[0].strip() if pd.notna(x) else x)
df_counterfact['corrupted_pair_output'] = df_counterfact['corrupted_pair'].apply(lambda x: convert_to_gas_format(parse_absa_string(x.split('[A] [O] [S]')[-1].strip()), spaced=True) if pd.notna(x) else x)
df_counterfact['corrupted_pair_gas'] = df_counterfact.apply(lambda row: f"{row['corrupted_pair_input']} => {row['corrupted_pair_output']}" if pd.notna(row['corrupted_pair_input']) and pd.notna(row['corrupted_pair_output']) else None, axis=1)

In [5]:
df_counterfact

,index,original_pair,corrupted_pair,original_pair_input,original_pair_output,original_pair_gas,corrupted_pair_input,corrupted_pair_output,corrupted_pair_gas
0,4,"tidak dapat snack . setelah di keluhan , baru ...","baik sangat radio . setelah di keluhan , baru ...","tidak dapat snack . setelah di keluhan , baru ...",( snack | tidak dapat | negative ),"tidak dapat snack . setelah di keluhan , baru ...","baik sangat radio . setelah di keluhan , baru ...",( radio | baik sangat | positive ),"baik sangat radio . setelah di keluhan , baru ..."
1,10,kamarnya oke . [A] [O] [S] [A] kamarnya [O] ok...,pot bunga busuk . [A] [O] [S] [A] pot bunga [...,kamarnya oke .,( kamarnya | oke | positive ),kamarnya oke . => ( kamarnya | oke | positive ),pot bunga busuk .,( pot bunga | busuk | negative ),pot bunga busuk . => ( pot bunga | busuk | ne...
2,18,tempat tdr kurang bersih . [A] [O] [S] [A] tem...,baju anakku cukup cepat . [A] [O] [S] [A] baju...,tempat tdr kurang bersih .,( tempat tidur | kurang bersih | negative ),tempat tdr kurang bersih . => ( tempat tidur |...,baju anakku cukup cepat .,( baju anakku | cukup cepat | positive ),baju anakku cukup cepat . => ( baju anakku | c...
3,50,tetapi sayangnya di kamar yang saya tempati ti...,tetapi sayangnya di kamar yang saya tempati ce...,tetapi sayangnya di kamar yang saya tempati ti...,( lampu tidur | tidak terdapat | negative ),tetapi sayangnya di kamar yang saya tempati ti...,tetapi sayangnya di kamar yang saya tempati ce...,( rekening tabungan | cepat sekali | positive ),tetapi sayangnya di kamar yang saya tempati ce...
4,54,tidak ada sarapan . [A] [O] [S] [A] sarapan [O...,baik sangat lilin . [A] [O] [S] [A] lilin [O] ...,tidak ada sarapan .,( sarapan | tidak ada | negative ),tidak ada sarapan . => ( sarapan | tidak ada |...,baik sangat lilin .,( lilin | baik sangat | positive ),baik sangat lilin . => ( lilin | baik sangat |...
...,...,...,...,...,...,...,...,...,...
95,2399,"terimakasih airy , layanannya sangat sangat ba...","erimakasih airy , peraturan pahit, moga kedepa...","terimakasih airy , layanannya sangat sangat ba...",( layanannya | sangat sangat baik | positive ),"terimakasih airy , layanannya sangat sangat ba...","erimakasih airy , peraturan pahit, moga kedepa...",( peraturan | pahit | negative ),"erimakasih airy , peraturan pahit, moga kedepa..."
96,2409,tidak ada lift . kesulitannya hanya mengangkut...,baik amat radio . kesulitannya hanya mengangku...,tidak ada lift . kesulitannya hanya mengangkut...,( lift | tidak ada | negative ),tidak ada lift . kesulitannya hanya mengangkut...,baik amat radio . kesulitannya hanya mengangku...,( radio | baik amat | positive ),baik amat radio . kesulitannya hanya mengangku...
97,2415,kamar bersih hotel berada disamping gran mall ...,angin kotor hotel berada disamping gran mall b...,kamar bersih hotel berada disamping gran mall ...,( kamar | bersih | positive ),kamar bersih hotel berada disamping gran mall ...,angin kotor hotel berada disamping gran mall b...,( angin | kotor | negative ),angin kotor hotel berada disamping gran mall b...
98,2458,karena terlalu banyak kamar jadi tidak diperha...,"tabil sekali , jadi proses berjalan sangat mul...",karena terlalu banyak kamar jadi tidak diperha...,( kebersihan | karena terlalu banyak kamar jad...,karena terlalu banyak kamar jadi tidak diperha...,"tabil sekali , jadi proses berjalan sangat mul...","( ekonomi | stabil sekali , jadi proses berjal...","tabil sekali , jadi proses berjalan sangat mul..."
99,2463,tidak ada wifi sesuai yang di iklankan . [A] [...,baiknya drum sesuai yang di iklankan . [A] [O]...,tidak ada wifi sesuai yang di iklankan .,( wifi | tidak ada | negative ),tidak ada wifi sesuai yang di iklankan . => ( ...,baiknya drum sesuai yang di iklankan .,( drum | baiknya | positive ),baiknya drum sesuai yang di iklankan . => ( dr...

In [6]:
df_counterfact[['index', 'original_pair_gas', 'corrupted_pair_gas']].rename({'original_pair_gas': 'original_pair', 'corrupted_pair_gas': 'corrupted_pair'}).to_csv('utils_notebooks/gas_counterfact_converted.csv', index=False)

## Whole dataset

In [3]:
dataset_folder = 'corrected_splitopinion_typocorrected_gas_arrow'
split = 'train'
lang = 'indo'
dataset_per_split = {}
for split in ['train', 'test']:
	dataset_path = f'hotel_dataset/{lang}/{dataset_folder}/hotel_aste_{split}_augmented{"_noreasoning" if split == "train" else ""}.json'
	with open(dataset_path, 'r') as f:
		data = json.load(f)
	dataset_per_split[split] = data

In [12]:
import re
def add_space_around_punctuation(text):
    # Except for '-'
    # Ensure space before punctuation
    text = re.sub(r'(\S)([.,!?\(\)\"\';:+/]+)', r'\1 \2', text)
    # Ensure space after punctuation
    text = re.sub(r'([.,!?\(\)\"\';:+/]+)(\S)', r'\1 \2', text)
    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)
    # Ensure punctuation sequences like '...' are split into spaced dots
    text = re.sub(r'([.]{2,})', lambda m: ' '.join(m.group(1)), text)
    return text.strip()

In [13]:
add_space_around_punctuation(dataset_per_split['train'][0]['target'])

'( ac , tidak berfungsi optimal , negative ) ; ( wifi koneksi , kurang stabil , negative )'

In [10]:
new_dataset_per_split = {}
for split in ['train', 'test']:
	new_data = []
	for item in dataset_per_split[split]:
		new_item = item.copy()
		new_item['target'] = add_space_around_punctuation(item['target'])
		new_data.append(new_item)
	new_dataset_per_split[split] = new_data

In [11]:
# Store the new dataset per split
for split in ['train', 'test']:
	output_path = f'hotel_dataset/{lang}/{dataset_folder}_spaced/hotel_aste_{split}_augmented{"_noreasoning" if split == "train" else ""}_gas.json'
	os.makedirs(os.path.dirname(output_path), exist_ok=True)
	with open(output_path, 'w') as f:
		json.dump(new_dataset_per_split[split], f, indent=4)

## GAS with |

In [11]:
dataset_folder = 'corrected_splitopinion_typocorrected_aos'
split = 'train'
lang = 'indo'
dataset_per_split = {}
for split in ['train', 'test']:
	dataset_path = f'hotel_dataset/{lang}/{dataset_folder}/hotel_aste_{split}_augmented{"_noreasoning" if split == "train" else ""}.json'
	with open(dataset_path, 'r') as f:
		data = json.load(f)
	dataset_per_split[split] = data

In [13]:
new_dataset_per_split = {}
for split in ['train', 'test']:
	new_data = []
	for item in dataset_per_split[split]:
		new_item = item.copy()
		new_item['input'] = new_item['input'].replace('[A] [O] [S]', '').strip() + ' =>'
		new_item['target'] = convert_to_gas_format(parse_absa_string(item['target']), spaced=True)
		new_data.append(new_item)
	new_dataset_per_split[split] = new_data

In [14]:
new_dataset_per_split

{'train': [{'sentence_id': 0,
   'instance_id': 0,
   'task_elements': 'aos',
   'input': 'kamar saya ada kendala di ac tidak berfungsi optimal . dan juga wifi koneksi kurang stabil . =>',
   'target': '( ac | tidak berfungsi optimal | negative ) ; ( wifi koneksi | kurang stabil | negative )',
   'element_order': 'aos'},
  {'sentence_id': 1,
   'instance_id': 5,
   'task_elements': 'aos',
   'input': 'tempatnya bagus . kolam renangnya bersih . =>',
   'target': '( tempatnya | bagus | positive ) ; ( kolam renangnya | bersih | positive )',
   'element_order': 'aos'},
  {'sentence_id': 2,
   'instance_id': 10,
   'task_elements': 'aos',
   'input': 'oke banget , tetapi ac nya tidak bisa diatur suhu nya . =>',
   'target': '( ac nya | tidak bisa diatur suhu nya | negative ) ; ( null | oke banget | positive )',
   'element_order': 'aos'},
  {'sentence_id': 3,
   'instance_id': 15,
   'task_elements': 'aos',
   'input': 'keren . nyaman semuanya . =>',
   'target': '( semuanya | nyaman | positive ) ; ( null | keren | positive )',
   'element_order': 'aos'},
  {'sentence_id': 4,
   'instance_id': 20,
   'task_elements': 'aos',
   'input': 'tidak dapat snack . setelah di keluhan , baru dikasik snacknya . =>',
   'target': '( snack | tidak dapat | negative )',
   'element_order': 'aos'},
  {'sentence_id': 5,
   'instance_id': 25,
   'task_elements': 'aos',
   'input': 'overall bagus . terjangkau . kapan kapam inap di airy room lagi deh . =>',
   'target': '( overall | bagus | positive ) ; ( null | terjangkau | positive )',
   'element_order': 'aos'},
  {'sentence_id': 6,
   'instance_id': 30,
   'task_elements': 'aos',
   'input': 'pelayanan mas nya sangat baik , membantu , ramah dan komunikatif , kamar sangat bersih , kamar mandi sangat baik . cuma air panasnya tidak bisa lama . =>',
   'target': '( pelayanan mas nya | sangat baik | positive ) ; ( pelayanan mas nya | membantu | positive ) ; ( pelayanan mas nya | ramah | positive ) ; ( pelayanan mas nya | komunikatif | positive ) ; ( kamar | sangat bersih | positive ) ; ( kamar mandi | sangat baik | positive ) ; ( air panasnya | tidak bisa lama | negative )',
   'element_order': 'aos'},
  {'sentence_id': 7,
   'instance_id': 35,
   'task_elements': 'aos',
   'input': 'airyroom ini sangat mengecewakan dalam hal layanan dan kebersihan kamar . =>',
   'target': '( layanan | sangat mengecewakan | negative ) ; ( kebersihan kamar | sangat mengecewakan | negative )',
   'element_order': 'aos'},
  {'sentence_id': 8,
   'instance_id': 40,
   'task_elements': 'aos',
   'input': 'agak perlu dibersihkan . kamar banyak semut . =>',
   'target': '( kamar | agak perlu dibersihkan | negative ) ; ( kamar | banyak semut | negative )',
   'element_order': 'aos'},
  {'sentence_id': 9,
   'instance_id': 45,
   'task_elements': 'aos',
   'input': 'pelayanan sangat buruk . mohon diperbaiki . =>',
   'target': '( pelayanan | sangat buruk | negative ) ; ( pelayanan | mohon diperbaiki | negative )',
   'element_order': 'aos'},
  {'sentence_id': 10,
   'instance_id': 50,
   'task_elements': 'aos',
   'input': 'kamarnya oke . =>',
   'target': '( kamarnya | oke | positive )',
   'element_order': 'aos'},
  {'sentence_id': 11,
   'instance_id': 55,
   'task_elements': 'aos',
   'input': 'saya sampai sanur itu sekitar pukul 20.00 wita mutermuter cari hotel ini , sampai telepon ke cs pun tidak cukup membantu kami menemukan hotel ini , kami tanya orang sekitar pun tidak ada yang tahu dimana ananda beach hotel ini . alamat tidak akurat sama sekali ! =>',
   'target': '( cs | tidak cukup membantu | negative ) ; ( alamat | tidak akurat sama sekali | negative )',
   'element_order': 'aos'},
  {'sentence_id': 12,
   'instance_id': 60,
   'task_elements': 'aos',
   'input': 'recomended , hotel dengan price murah tetapi fasilitas oke punya . makanannya juga oke , pelayanan oke , bapak . =>',
   'target': '( price | murah | positive ) ; ( fasilitas | oke | positive ) ; ( makanannya | oke | positive ) ; ( pelayanan | oke | positive ) ; ( null | recommended | positive )',
   'element_order': 'aos'},
  {'sentence_id': 13,
   'instance_id': 65,
   'task_elements': 'aos',
   'input': 'fasilitas lengkap . dapat snack juga dari airy . terimakasih airy . =>',
   'target': '( fasilitas | lengkap | positive ) ; ( snack | dapat | positive )',
   'element_order': 'aos'},
  {'sentence_id': 14,
   'instance_id': 70,
   'task_elements': 'aos',
   'input': 'pelayanan nya sangat bagus . kamar nya juga oke . =>',
   'target': '( pelayanan nya | sangat bagus | positive ) ; ( kamar nya | oke | positive )',
   'element_order': 'aos'},
  {'sentence_id': 15,
   'instance_id': 75,
   'task_elements': 'aos',
   'input': 'kamar cukup luas , interior menarik dan unik sekali , penempatan furniture tepat , suka banget dengan kamar mandinya , walpaper kamar beragam , pencahayaan dibuat dramatis , tidak terlalu terang tetapi baguss . hanya saja tidak tersedia sarapan , naik ke lantai 1 dengan tangga , lift tidak berfungsi . =>',
   'target': '( kamar | cukup luas | positive ) ; ( interior | menarik | positive ) ; ( interior | unik sekali | positive ) ; ( penempatan furniture | tepat | positive ) ; ( kamar mandinya | suka banget | positive ) ; ( walpaper kamar | beragam | positive ) ; ( pencahayaan | dibuat dramatis | positive ) ; ( pencahayaan | tidak terlalu terang | negative ) ; ( pencahayaan | baguss | positive ) ; ( sarapan | tidak tersedia | negative ) ; ( lift | naik ke lantai 1 dengan tangga , lift tidak berfungsi | negative )',
   'element_order': 'aos'},
  {'sentence_id': 16,
   'instance_id': 80,
   'task_elements': 'aos',
   'input': 'lokasi strategis harga terjangkau bangunan lama memang , tetapi dengan harga yang terjangkau dan lokasi tengah kota sangat worthy dan sudah 3x ini menginap di sini wifi kencang dapat sarapan pula , menu homey tetapi tasty keamanan 24jam ramahramah overall bagus . =>',
   'target': '( lokasi | strategis | positive ) ; ( harga | terjangkau | positive ) ; ( null | bangunan lama | negative ) ; ( lokasi | tengah kota | positive ) ; ( null | sangat worthy | positive ) ; ( wifi | kencang | positive ) ; ( sarapan | dapat | positive ) ; ( menu | homey | positive ) ; ( menu | tasty | positive ) ; ( keamanan | 24 jam | positive ) ; ( null | ramah ramah | positive ) ; ( overall | bagus | positive )',
   'element_order': 'aos'},
  {'sentence_id': 17,
   'instance_id': 85,
   'task_elements': 'aos',
   'input': 'nyaman banget kamarnya . bersiih . dan buat betah . next klau kesana bisa jadi rekomendasi buat tempat tinggal sementara . =>',
   'target': '( kamarnya | nyaman banget | positive ) ; ( kamarnya | bersih | positive ) ; ( kamarnya | buat betah | positive ) ; ( null | next kalau ke sana bisa jadi rekomendasi buat tempat tinggal sementara | positive )',
   'element_order': 'aos'},
  {'sentence_id': 18,
   'instance_id': 90,
   'task_elements': 'aos',
   'input': 'tempat tdr kurang bersih . =>',
   'target': '( tempat tidur | kurang bersih | negative )',
   'element_order': 'aos'},
  {'sentence_id': 19,
   'instance_id': 95,
   'task_elements': 'aos',
   'input': 'tempat nya nyaman dan harga nya pun terjangkau , cocok sekali untuk liburan keluarga . =>',
   'target': '( tempat nya | nyaman | positive ) ; ( harga nya | terjangkau | positive ) ; ( null | cocok sekali untuk liburan keluarga | positive )',
   'element_order': 'aos'},
  {'sentence_id': 20,
   'instance_id': 100,
   'task_elements': 'aos',
   'input': 'kamar oke . ac kurang dingin . lampu kamar mandi ada yang mati . =>',
   'target': '( kamar | oke | positive ) ; ( ac | kurang dingin | negative ) ; ( lampu kamar mandi | ada yang mati | negative )',
   'element_order': 'aos'},
  {'sentence_id': 21,
   'instance_id': 105,
   'task_elements': 'aos',
   'input': 'kamar luas dan kedap , bersih makanan enak . dan lokasi strategis . =>',
   'target': '( kamar | luas | positive ) ; ( kamar | kedap | positive ) ; ( kamar | bersih | positive ) ; ( makanan | enak | positive ) ; ( lokasi | strategis | positive )',
   'element_order': 'aos'},
  {'sentence_id': 22,
   'instance_id': 110,
   'task_elements': 'aos',
   'input': 'semuanya sudah baik tetapi didalam kamar tidak ada tempat untuk menggantungkan baju atau celana . =>',
   'target': '( semuanya | sudah baik | positive ) ; ( kamar | tidak ada tempat untuk menggantungkan baju atau celana | negative )',
   'element_order': 'aos'},
  {'sentence_id': 23,
   'instance_id': 115,
   'task_elements': 'aos',
   'input': 'hanya wifi yang kurang memuaskan , wifi tidak bisa dipakai , selebihnya tidak masalah . =>',
   'target': '( wifi | kurang memuaskan | negative ) ; ( wifi | tidak bisa dipakai | negative ) ; ( selebihnya | tidak masalah | positive )',
   'element_order': 'aos'},
  {'sentence_id': 24,
   'instance_id': 120,
   'task_elements': 'aos',
   'input': 'breakfastnya bervariasi dan sehat . thank you for servicing . =>',
   'target': '( breakfastnya | bervariasi | positive ) ; ( breakfastnya | sehat | positive )',
   'element_order': 'aos'},
  {'sentence_id': 25,
   'instance_id': 125,
   'task_elements': 'aos',
   'input': 'kamar bersih , kasur bersih ( aku paling cepat bereaksi kalau ada tungau walau cma sedikit ) , 24 jam petugasnya siap sedia buat bantuin . top deh ! =>',
   'target': '( kamar | bersih | positive ) ; ( kasur | bersih | positive ) ; ( petugasnya | 24 jam petugasnya siap sedia buat bantuin | positive ) ; ( null | top | positive )',
   'element_order': 'aos'},
  {'sentence_id': 26,
   'instance_id': 130,
   'task_elements': 'aos',
   'input': 'bersih , rapi , tetapi properti nya kurang diperlengkapi , kurang nyaman juga karena banyak kebisingan , apalagi dari ruangan aula nya karena ada acara . =>',
   'target': '( properti nya | kurang diperlengkapi | negative ) ; ( null | kurang nyaman juga karena banyak kebisingan , apalagi dari ruangan aula nya karena ada acara | negative ) ; ( null | bersih | positive ) ; ( null | rapi | positive )',
   'element_order': 'aos'},
  {'sentence_id': 27,
   'instance_id': 135,
   'task_elements': 'aos',
   'input': 'terlalu sempit kamarnya , tetapi lumayanlah dengan budget yang segitu , pelayanan hotel juga lumayan bagus dan ramah , airy memang joss . =>',
   'target': '( kamarnya | terlalu sempit | negative ) ; ( kamarnya | lumayanlah dengan budget yang segitu | positive ) ; ( pelayanan hotel | lumayan bagus | positive ) ; ( pelayanan hotel | ramah | positive ) ; ( airy | joss | positive )',
   'element_order': 'aos'},
  {'sentence_id': 28,
   'instance_id': 140,
   'task_elements': 'aos',
   'input': 'begitu masuk pertama , kesan yang diterima adalah jorok . mohon maaf , ada kotoran ( eek ) masih melekat di bibir kloset . seperti tidak dibersihkan . kemudian semakin malam , banyak kecoak bermunculan , awalnya saya baca review dari app tetangga yang bilang banyak kecoak , saya tidak percaya . tetapi begitu mengalami sendiri , sangat horor , tidur jadi tidak nyenyak . =>',
   'target': '( bibir kloset | ada kotoran ( eek ) masih melekat | negative ) ; ( bibir kloset | seperti tidak dibersihkan | negative ) ; ( null | jorok | negative ) ; ( null | banyak kecoak bermunculan | negative ) ; ( null | sangat horor , tidur jadi tidak nyenyak | negative )',
   'element_order': 'aos'},
  {'sentence_id': 29,
   'instance_id': 145,
   'task_elements': 'aos',
   'input': 'saya salah dikasih kamar , tidak ada handuk , gayung , airy pack , kasur tidak pakai seprai , lemari juga kotor . =>',
   'target': '( kamar | saya salah dikasih kamar | negative ) ; ( handuk | tidak ada | negative ) ; ( gayung | tidak ada | negative ) ; ( airy pack | tidak ada | negative ) ; ( kasur | tidak pakai seprai | negative ) ; ( lemari | kotor | negative )',
   'element_order': 'aos'},
  {'sentence_id': 30,
   'instance_id': 150,
   'task_elements': 'aos',
   'input': 'bersih . tetapi sulit ditemukan . =>',
   'target': '( null | bersih | positive ) ; ( null | sulit ditemukan | negative )',
   'element_order': 'aos'},
  {'sentence_id': 31,
   'instance_id': 155,
   'task_elements': 'aos',
   'input': 'lampu kamar tidak menyala . yang lain oke laah . topp . =>',
   'target': '( lampu kamar | tidak menyala | negative ) ; ( yang lain | oke lah . top | positive )',
   'element_order': 'aos'},
  {'sentence_id': 32,
   'instance_id': 160,
   'task_elements': 'aos',
   'input': 'nyaman . =>',
   'target': '( null | nyaman | positive )',
   'element_order': 'aos'},
  {'sentence_id': 33,
   'instance_id': 165,
   'task_elements': 'aos',
   'input': 'bagus bersih nyaman , cuma tempat terlalu kedalam . =>',
   'target': '( tempat | terlalu ke dalam | negative ) ; ( null | bagus | positive ) ; ( null | bersih | positive ) ; ( null | nyaman | positive )',
   'element_order': 'aos'},
  {'sentence_id': 34,
   'instance_id': 170,
   'task_elements': 'aos',
   'input': 'mantap , lokasi strategis , ke tanah abang bisa jalan kaki . cuma karena tempat tidur diatas agak ngerih , bunyibunyi takut jatuh hai . =>',
   'target': '( lokasi | strategis | positive ) ; ( lokasi | ke tanah abang bisa jalan kaki | positive ) ; ( tempat tidur | karena tempat tidur di atas agak ngeri | negative ) ; ( tempat tidur | bunyi bunyi takut jatuh | negative ) ; ( null | mantap | positive )',
   'element_order': 'aos'},
  {'sentence_id': 35,
   'instance_id': 175,
   'task_elements': 'aos',
   'input': 'hotelnya bagus , pelayanan oke , dekat dengan fasilitas umum . terimakasih . =>',
   'target': '( hotelnya | bagus | positive ) ; ( pelayanan | oke | positive ) ; ( hotelnya | dekat dengan fasilitas umum | positive )',
   'element_order': 'aos'},
  {'sentence_id': 36,
   'instance_id': 180,
   'task_elements': 'aos',
   'input': 'over all enak menginap disini , lokasinya strategis jadi kalau mau berasa turis bisa jalan kaki kemana mana . dan yang lebih berasa turisnya ketika malam mau ke lagi jalan kaki dan sekeliling lagi ada proyek pembangunan begitu tertawa . oiya ac nya sempat netes juga sih tetapi tidak apaapa lah bisa diatasi . =>',
   'target': '( over all | enak menginap disini | positive ) ; ( lokasinya | strategis | positive ) ; ( ac nya | sempat netes juga sih | negative ) ; ( ac nya | tidak apaapa lah bisa diatasi | positive )',
   'element_order': 'aos'},
  {'sentence_id': 37,
   'instance_id': 185,
   'task_elements': 'aos',
   'input': 'lumayan bersih tetapi lantainya tidak rata karena kurang semen di bawah nya , jadi menyebabkan pecah " . =>',
   'target': '( lantainya | tidak rata karena kurang semen di bawah nya , jadi menyebabkan pecah pecah | negative ) ; ( null | lumayan bersih | positive )',
   'element_order': 'aos'},
  {'sentence_id': 38,
   'instance_id': 190,
   'task_elements': 'aos',
   'input': 'bersih . ramah . strategis . =>',
   'target': '( null | bersih | positive ) ; ( null | ramah | positive ) ; ( null | strategis | positive )',
   'element_order': 'aos'},
  {'sentence_id': 39,
   'instance_id': 195,
   'task_elements': 'aos',
   'input': '2 kali inap di situ dengan kamar yang berbeda tetapi sama saja kamar mandi tetap bau . =>',
   'target': '( kamar mandi | 2 kali inap di situ dengan kamar yang berbeda tetapi sama saja kamar mandi tetap bau | negative )',
   'element_order': 'aos'},
  {'sentence_id': 40,
   'instance_id': 200,
   'task_elements': 'aos',
   'input': 'tidak sesuai dengan di foto . =>',
   'target': '( null | tidak sesuai dengan di foto | positive )',
   'element_order': 'aos'},
  {'sentence_id': 41,
   'instance_id': 205,
   'task_elements': 'aos',
   'input': 'pelayanan si masnya sangat ramah , saya sudah berlangganan di airy eco deplu hampir setengah tahun . kamarnya rapi , fasilitas lengkap , dan its cheap ! =>',
   'target': '( pelayanan | sangat ramah | positive ) ; ( kamarnya | rapi | positive ) ; ( fasilitas | lengkap | positive ) ; ( null | cheap | positive )',
   'element_order': 'aos'},
  {'sentence_id': 42,
   'instance_id': 210,
   'task_elements': 'aos',
   'input': 'hotel yang berbasis syariah , sangat baik untuk business traveler karena berada di tengah kota dengan rate yang wajar , wifi yang disediakan tidak hanya sebagai syarat ada wifi saja namun kecepatan yang diberikan sangat baik . =>',
   'target': '( wifi | wifi yang disediakan tidak hanya sebagai syarat ada wifi saja namun kecepatan yang diberikan sangat baik | positive ) ; ( hotel | sangat baik untuk business traveler karena berada di tengah kota dengan rate yang wajar | positive )',
   'element_order': 'aos'},
  {'sentence_id': 43,
   'instance_id': 215,
   'task_elements': 'aos',
   'input': 'kamar bersih , nyaman sekali , csnya ramah mantaplah , dan daerahnya tenang . =>',
   'target': '( kamar | bersih | positive ) ; ( kamar | nyaman sekali | positive ) ; ( csnya | ramah | positive ) ; ( csnya | mantaplah | positive ) ; ( daerahnya | tenang | positive )',
   'element_order': 'aos'},
  {'sentence_id': 44,
   'instance_id': 220,
   'task_elements': 'aos',
   'input': 'nyaman . dapat snack , hanya saja dikasih lantai 3 . =>',
   'target': '( snack | dapat | positive ) ; ( null | nyaman | positive ) ; ( null | hanya saja dikasih lantai 3 | negative )',
   'element_order': 'aos'},
  {'sentence_id': 45,
   'instance_id': 225,
   'task_elements': 'aos',
   'input': 'memuaskan dan dekat dengan bandara . =>',
   'target': '( null | memuaskan | positive ) ; ( null | dekat dengan bandara | positive )',
   'element_order': 'aos'},
  {'sentence_id': 46,
   'instance_id': 230,
   'task_elements': 'aos',
   'input': 'resepsionis tidak ada etika , tidak sopan suka marah , kamar berisik tiap siang dan malam tidak bisa istirahat . =>',
   'target': '( resepsionis | tidak ada etika | negative ) ; ( resepsionis | tidak sopan | negative ) ; ( resepsionis | suka marah | negative ) ; ( kamar | berisik tiap siang dan malam tidak bisa istirahat | negative )',
   'element_order': 'aos'},
  {'sentence_id': 47,
   'instance_id': 235,
   'task_elements': 'aos',
   'input': 'lampu remang - remang , kamar mandi kotor , menginap 10 hari tetapi hanya diberikan peralatan mandi sekali saja saat pertama masuk . =>',
   'target': '( lampu | remang - remang | negative ) ; ( kamar mandi | kotor | negative ) ; ( peralatan mandi | menginap 10 hari tetapi hanya diberikan peralatan mandi sekali saja | negative )',
   'element_order': 'aos'},
  {'sentence_id': 48,
   'instance_id': 240,
   'task_elements': 'aos',
   'input': 'sudah capek dari bandung pingin istirahat . sudah dapat kamar , eh ac rusak bahkan dapat kipas angin . walau dapat pot 50000 . trakhr bangun tdr masuk angin . tempatnya bagus tetapi begitu kalau soal pelayanan harus di tingkatkan lagi dan kurang ramah . =>',
   'target': '( ac | rusak | negative ) ; ( tempatnya | bagus | positive ) ; ( pelayanan | harus ditingkatkan lagi | negative ) ; ( pelayanan | kurang ramah | negative ) ; ( potongan | dapat | positive )',
   'element_order': 'aos'},
  {'sentence_id': 49,
   'instance_id': 245,
   'task_elements': 'aos',
   'input': 'kamar kecil dan kurang nyaman . =>',
   'target': '( kamar | kecil | negative ) ; ( kamar | kurang nyaman | negative )',
   'element_order': 'aos'},
  {'sentence_id': 50,
   'instance_id': 250,
   'task_elements': 'aos',
   'input': 'tetapi sayangnya di kamar yang saya tempati tidak terdapat lampu tidur . =>',
   'target': '( lampu tidur | tidak terdapat | negative )',
   'element_order': 'aos'},
  {'sentence_id': 51,
   'instance_id': 255,
   'task_elements': 'aos',
   'input': 'kamar airy terburuk yang pernah saya singgahi , kamar bau , tidak wifi , sinyal tidak bisa masuk kamar , toilet buruk , pulangpulang dikira ambil bantal airy padahal memang tidak ada bantal airy tidak recomended , nyesal menginap disini . =>',
   'target': '( kamar airy | terburuk | negative ) ; ( kamar | bau | negative ) ; ( wifi | sinyal tidak bisa masuk | negative ) ; ( toilet | buruk | negative ) ; ( bantal airy | tidak ada | negative ) ; ( null | tidak recommended | negative ) ; ( null | nyesal menginap | negative )',
   'element_order': 'aos'},
  {'sentence_id': 52,

In [15]:
# Save the new dataset per split
for split in ['train', 'test']:
	output_path = f'hotel_dataset/{lang}/corrected_splitopinion_typocorrected_gas_arrow_bar/hotel_aste_{split}_augmented{"_noreasoning" if split == "train" else ""}_gas.json'
	os.makedirs(os.path.dirname(output_path), exist_ok=True)
	with open(output_path, 'w') as f:
		json.dump(new_dataset_per_split[split], f, indent=4)