In [1]:
import pandas as pd
import numpy as np
import json
import re
from ast import literal_eval
import importlib
from dotenv import load_dotenv
import os
os.chdir('..')

In [2]:
# Load environment variables from .env file
load_dotenv()

True

In [3]:
# Set GEMINI_API_KEY environment variable with your API key
os.environ['GEMINI_API_KEY'] = os.getenv('GEMINI_API_KEY')

In [4]:
import base64
from google import genai
from google.genai import types
from copy import deepcopy

In [5]:
def generate(prompt):
	client = genai.Client(
			api_key=os.environ.get("GEMINI_API_KEY"),
		)

	model = "gemini-2.5-flash"
	contents = [
		types.Content(
			role="user",
			parts=[
				types.Part.from_text(
					text=prompt
				),
			],
		),
	]
	generate_content_config = types.GenerateContentConfig(
		temperature=0.75,
		top_p=0.9,
		top_k=40,
		max_output_tokens=8192,
		thinking_config=types.ThinkingConfig(thinking_budget=-1), # Dynamic thinking = -1, no thinking = 0
		response_mime_type="application/json",
		system_instruction=[
			types.Part.from_text(
				text="""You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and English."""
			),
		],
	)
		
	response = client.models.generate_content(
		model=model, contents=contents, config=generate_content_config
	)
	# print(response.text)
	return response

from typing import List, Dict
import re
def parse_absa_string(text: str) -> List[Dict[str, str]]:
    """
    Parses a string formatted as "[A] aspect [O] opinion [S] sentiment" into a list of dictionaries.
    Each dictionary contains the tag as the key and the corresponding value.
    For example, "[A] [O] [S] [A] harga [O] terjangkau [S] positive [SSEP] [A] fasilitas [O] nyaman [S] positive" becomes:
    [{'A': 'harga', 'S': 'positive', 'O': 'terjangkau'},
    {'A': 'fasilitas', 'S': 'positive', 'O': 'nyaman'}].

    Args:
        text (str): ABSA string output to be parsed.

    Returns:
        List[Dict[str, str]]: List of dictionaries of parsed ABSA output.

    """
    pattern = r"\[(\w+)\]\s*([^[]+)"
    matches = re.findall(pattern, text)

    result = []
    current_dict = {}

    for tag, content in matches:
        if tag == "SSEP":  # Sentence separator -> Start a new dictionary
            result.append(current_dict)
            current_dict = {}
        else:
            current_dict[tag] = content.strip()

    if current_dict:  # Append the last sentence if it exists
        result.append(current_dict)

    return result

In [6]:
dataset_folder = 'corrected_splitopinion_typocorrected'
lang = 'indo'
split = 'test'
dataset_path = f'hotel_dataset/{lang}/{dataset_folder}/hotel_aste_{split}_augmented{"_noreasoning" if split == "train" else ""}.json'
with open(dataset_path, 'r') as f:
	dataset = json.load(f)

In [7]:
dataset_unique = []
for instance in dataset:
	if instance['element_order'] == 'aos':
		dataset_unique.append(deepcopy(instance))

In [8]:
dataset_single_triplet = []
for instance in dataset_unique:
	triplets = parse_absa_string(instance['target'])
	for triplet in triplets:
		new_instance = deepcopy(instance)
		new_instance['target'] = f"[A] {triplet.get('A', '')} [O] {triplet.get('O', '')} [S] {triplet.get('S', '')}"
		dataset_single_triplet.append(new_instance)

In [9]:
df_dataset = pd.DataFrame(dataset_unique)
df_dataset

,sentence_id,instance_id,task_elements,input,target,element_order
0,3500,17500,aos,pelayanan nya sangat ramah . [A] [O] [S],[A] pelayanan nya [O] sangat ramah [S] positive,aos
1,3501,17505,aos,sayang wifi tidak bagus harus keluar kamar . [...,[A] wifi [O] tidak bagus harus keluar kamar [S...,aos
2,3502,17510,aos,"tulisannya twin bed , tetapi yang ada kamarnya...",[A] kamarnya [O] beda [S] negative,aos
3,3503,17515,aos,"over all baik , hanya sja akan lebih memuaskan...",[A] over all [O] baik [S] positive [SSEP] [A] ...,aos
4,3504,17520,aos,fasilatas sesuia . [A] [O] [S],[A] fasilitas [O] sesuai [S] positive,aos
...,...,...,...,...,...,...
995,4495,22475,aos,"lumayan , harga murah banged . [A] [O] [S]",[A] harga [O] murah banget [S] positive [SSEP]...,aos
996,4496,22480,aos,buat lakilaki dan perempuan yang belum menikah...,[A] null [O] buat laki laki dan perempuan yang...,aos
997,4497,22485,aos,"kamar sangat nyaman dan bersih , sungguh menye...",[A] kamar [O] sangat nyaman [S] positive [SSEP...,aos
998,4498,22490,aos,"kamarnya luas , kasurnya empuk , kamar mandiny...",[A] kamarnya [O] luas [S] positive [SSEP] [A] ...,aos
999,4499,22495,aos,"kamar tidak sesuai , tempat parkir kurang nyam...",[A] kamar [O] tidak sesuai [S] negative [SSEP]...,aos

In [10]:
with open(f'utils_notebooks/prompt_translate/translate-triplet-eng.txt', 'r') as f:
	prompt_template = f.read()
print(prompt_template)

## Task Description
You will be given input-output pairs of Aspect Sentiment Triplet Extraction.
Given an Indonesian text and triplets consist of aspect term, opinion term, and sentiment polarity of the Indonesian text, translate all of them to English.
The order of each triplet is (aspect term, opinion term, sentiment polarity).
Below is the definition of each element in the triplet:
- The aspect term refers to a specific feature, attribute, or aspect of a product or service on which a user can express an opinion. Explicit aspect terms appear explicitly as a substring of the given text. The aspect term might be “NULL” for the implicit aspect.
- The sentiment polarity refers to the degree of positivity, negativity or neutrality expressed in the opinion towards a particular aspect or feature of a product or service, and the available polarities include: “positive”, “negative” and “neutral”. “neutral” means mildly positive or mildly negative.
- The opinion term refers to the sentiment or attitude expressed by a user towards a particular aspect or feature of a product or service. Explicit opinion terms appear explicitly as a substring of the given text. The opinion term might be "NULL" for the implicit opinion.

For the special case when the triplet is empty, just return an empty list for the translated triplet component.

## Step-by-step Instruction
1. Carefully read the sentence and its triplets to understand the context.
2. Translate the sentence, maintaining the original meaning, tone, style, and cultural nuances.
3. Translate the triplets of the sentence. Ensure that all elements of the triplet still matches the sentence. The translated aspect term and the opinion term must exist literally in the translated sentence. Do not make up your own words for the triplet translation part.
4. Ensure that any idiomatic expressions are adapted appropriately to fit the target language.
5. Review the translation for any grammatical or syntactical errors.
6. Write the translations in json format.

### Example:
Text Input: "sebenarnya kamar baik tetapi kurang profesional , di kasih tahu sarapan nasi goreng , minta di antar jam 8.30 ehh datang jam 9 itu pun di telepon dulu dan yang datang bahkan mie muah telor . hm ."
Triplets: [(kamar, baik, positive), (null, kurang profesional, negative)]
Output:
{
    "translated_text": "The room was actually good, but it was unprofessional. We were told breakfast would be fried rice and requested it to be delivered at 8:30 AM. However, it only arrived at 9 AM after we had to call, and instead of fried rice, they brought instant noodles with egg.",
    "translated_triplets": [
        {
            "aspect_term": "room",
            "opinion_term": "good",
            "sentiment_polarity": "positive"
        },
        {
            "aspect_term": "null",
            "opinion_term": "unprofessional",
            "sentiment_polarity": "negative"
        }
    ]
}

### Inference:

Text Input: {text-input}
Triplets: {input-triplets}
Output:

### Individual API request

In [36]:
from tqdm import tqdm
from time import sleep
from ast import literal_eval

outputs = {}
outputs_text = {}
for idx, row in tqdm(df_dataset.iterrows(), desc="Translating triplets", total=df_dataset.shape[0]):
	input_text = row['input'].replace('[A] [O] [S]', '').strip()
	triplets = parse_absa_string(row['target'])
	target_text = []
	for triplet in triplets:
		target_text.append(f"({triplet.get('A', 'err_empty')}, {triplet.get('O', 'err_empty')}, {triplet.get('S', 'err_empty')})")
	target_text = '[' + ', '.join(target_text) + ']'
	prompt = prompt_template.replace('{text-input}', input_text).replace('{input-triplets}', target_text)
	while True:
		try:
			output = generate(prompt)
			outputs[idx] = output
			outputs_text[idx] = literal_eval(output.text)
			outputs_text[idx]['text'] = input_text
			outputs_text[idx]['triplets'] = target_text
			break
		except Exception as e:
			print(f"Error: {e}")
			sleep(3.0)  # Wait for 3 seconds before retrying
			continue
	
	# Write to json file after each successful generation
	os.makedirs(f'temp/translation_output/eng/{dataset_folder}', exist_ok=True)
	with open(f'temp/translation_output/eng/{dataset_folder}/{os.path.basename(dataset_path)}', 'w') as f:
		json.dump(outputs_text, f, indent=4, ensure_ascii=False)
	
	if idx == 10:
		break

Translating triplets:   0%|          | 10/2482 [00:59<4:06:51,  5.99s/it]

### Batch API request

In [11]:
inline_requests = []
for idx, row in df_dataset.iterrows():
	input_text = row['input'].replace('[A] [O] [S]', '').strip()
	triplets = parse_absa_string(row['target'])
	target_text = []
	for triplet in triplets:
		target_text.append(f"({triplet.get('A', 'err_empty')}, {triplet.get('O', 'err_empty')}, {triplet.get('S', 'err_empty')})")
	target_text = '[' + ', '.join(target_text) + ']'
	prompt = prompt_template.replace('{text-input}', input_text).replace('{input-triplets}', target_text)
	
	inline_request = {
		"contents": [
			{
				"role": "user",
				"parts": [
					{
						"text": prompt
					}
				]
			}
		],
		"config": {
			"temperature": 0.75,
			"top_p": 0.9,
			"top_k": 40,
			"max_output_tokens": 8192,
			"thinking_config": {
				"thinking_budget": -1
			},
			"response_mime_type": "application/json",
			"system_instruction": [
				{
					"text": "You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and English."
				}
			]
		}
	}
	inline_requests.append(inline_request)

In [12]:
len(inline_requests)

1000

In [13]:
inline_requests[40]

{'contents': [{'role': 'user',
   'parts': [{'text': '## Task Description\nYou will be given input-output pairs of Aspect Sentiment Triplet Extraction.\nGiven an Indonesian text and triplets consist of aspect term, opinion term, and sentiment polarity of the Indonesian text, translate all of them to English.\nThe order of each triplet is (aspect term, opinion term, sentiment polarity).\nBelow is the definition of each element in the triplet:\n- The aspect term refers to a specific feature, attribute, or aspect of a product or service on which a user can express an opinion. Explicit aspect terms appear explicitly as a substring of the given text. The aspect term might be “NULL” for the implicit aspect.\n- The sentiment polarity refers to the degree of positivity, negativity or neutrality expressed in the opinion towards a particular aspect or feature of a product or service, and the available polarities include: “positive”, “negative” and “neutral”. “neutral” means mildly positive or mildly negative.\n- The opinion term refers to the sentiment or attitude expressed by a user towards a particular aspect or feature of a product or service. Explicit opinion terms appear explicitly as a substring of the given text. The opinion term might be "NULL" for the implicit opinion.\n\nFor the special case when the triplet is empty, just return an empty list for the translated triplet component.\n\n## Step-by-step Instruction\n1. Carefully read the sentence and its triplets to understand the context.\n2. Translate the sentence, maintaining the original meaning, tone, style, and cultural nuances.\n3. Translate the triplets of the sentence. Ensure that all elements of the triplet still matches the sentence. The translated aspect term and the opinion term must exist literally in the translated sentence. Do not make up your own words for the triplet translation part.\n4. Ensure that any idiomatic expressions are adapted appropriately to fit the target language.\n5. Review the translation for any grammatical or syntactical errors.\n6. Write the translations in json format.\n\n### Example:\nText Input: "sebenarnya kamar baik tetapi kurang profesional , di kasih tahu sarapan nasi goreng , minta di antar jam 8.30 ehh datang jam 9 itu pun di telepon dulu dan yang datang bahkan mie muah telor . hm ."\nTriplets: [(kamar, baik, positive), (null, kurang profesional, negative)]\nOutput:\n{\n    "translated_text": "The room was actually good, but it was unprofessional. We were told breakfast would be fried rice and requested it to be delivered at 8:30 AM. However, it only arrived at 9 AM after we had to call, and instead of fried rice, they brought instant noodles with egg.",\n    "translated_triplets": [\n        {\n            "aspect_term": "room",\n            "opinion_term": "good",\n            "sentiment_polarity": "positive"\n        },\n        {\n            "aspect_term": "null",\n            "opinion_term": "unprofessional",\n            "sentiment_polarity": "negative"\n        }\n    ]\n}\n\n### Inference:\n\nText Input: untuk resepsionis perlu di perbaiki supaya lebih ramah dan sopan terimakasih .\nTriplets: [(resepsionis, perlu di perbaiki supaya lebih ramah dan sopan, negative)]\nOutput:\n'}]}],
 'config': {'temperature': 0.75,
  'top_p': 0.9,
  'top_k': 40,
  'max_output_tokens': 8192,
  'thinking_config': {'thinking_budget': -1},
  'response_mime_type': 'application/json',
  'system_instruction': [{'text': 'You are an expert in Natural Language Processing. You are also linguist with an expertise in Indonesian and English.'}]}}

In [14]:
print(inline_requests[41]['contents'][0]['parts'][0]['text'])

## Task Description
You will be given input-output pairs of Aspect Sentiment Triplet Extraction.
Given an Indonesian text and triplets consist of aspect term, opinion term, and sentiment polarity of the Indonesian text, translate all of them to English.
The order of each triplet is (aspect term, opinion term, sentiment polarity).
Below is the definition of each element in the triplet:
- The aspect term refers to a specific feature, attribute, or aspect of a product or service on which a user can express an opinion. Explicit aspect terms appear explicitly as a substring of the given text. The aspect term might be “NULL” for the implicit aspect.
- The sentiment polarity refers to the degree of positivity, negativity or neutrality expressed in the opinion towards a particular aspect or feature of a product or service, and the available polarities include: “positive”, “negative” and “neutral”. “neutral” means mildly positive or mildly negative.
- The opinion term refers to the sentiment or attitude expressed by a user towards a particular aspect or feature of a product or service. Explicit opinion terms appear explicitly as a substring of the given text. The opinion term might be "NULL" for the implicit opinion.

For the special case when the triplet is empty, just return an empty list for the translated triplet component.

## Step-by-step Instruction
1. Carefully read the sentence and its triplets to understand the context.
2. Translate the sentence, maintaining the original meaning, tone, style, and cultural nuances.
3. Translate the triplets of the sentence. Ensure that all elements of the triplet still matches the sentence. The translated aspect term and the opinion term must exist literally in the translated sentence. Do not make up your own words for the triplet translation part.
4. Ensure that any idiomatic expressions are adapted appropriately to fit the target language.
5. Review the translation for any grammatical or syntactical errors.
6. Write the translations in json format.

### Example:
Text Input: "sebenarnya kamar baik tetapi kurang profesional , di kasih tahu sarapan nasi goreng , minta di antar jam 8.30 ehh datang jam 9 itu pun di telepon dulu dan yang datang bahkan mie muah telor . hm ."
Triplets: [(kamar, baik, positive), (null, kurang profesional, negative)]
Output:
{
    "translated_text": "The room was actually good, but it was unprofessional. We were told breakfast would be fried rice and requested it to be delivered at 8:30 AM. However, it only arrived at 9 AM after we had to call, and instead of fried rice, they brought instant noodles with egg.",
    "translated_triplets": [
        {
            "aspect_term": "room",
            "opinion_term": "good",
            "sentiment_polarity": "positive"
        },
        {
            "aspect_term": "null",
            "opinion_term": "unprofessional",
            "sentiment_polarity": "negative"
        }
    ]
}

### Inference:

Text Input: ada kolam renangnya yang buat anak senang .
Triplets: [(kolam renangnya, ada kolam renangnya yang buat anak senang, positive)]
Output:

In [15]:
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

In [16]:
print(f'Creating batch job with {len(inline_requests)} requests.')
inline_batch_job = client.batches.create(
    model="models/gemini-2.5-flash",
    src=inline_requests,
    config={
        'display_name': f"job-translation-{lang}-1",
    },
)

print(f"Created batch job: {inline_batch_job.name}")

Creating batch job with 1000 requests.
Created batch job: batches/5crm0h0t2580p641oyxpdhpku0q5h9o8ahzp

In [17]:
# List all batches
batches = client.batches.list()
for batch in batches:
    print(f"Batch ID: {batch.name}, State: {batch.state.name}")

Batch ID: batches/5crm0h0t2580p641oyxpdhpku0q5h9o8ahzp, State: JOB_STATE_PENDING
Batch ID: batches/sde88za41ogfgscv3eg94ezopyjeirkhiu1x, State: JOB_STATE_SUCCEEDED
Batch ID: batches/evg9i1wyd8gvczvytcxt9omherlhibe0vtum, State: JOB_STATE_SUCCEEDED
Batch ID: batches/xr5ky0oempio6kujvbxemftbm98goz78mw23, State: JOB_STATE_SUCCEEDED

In [18]:
from time import sleep

# Use the name of the job you want to check
# e.g., inline_batch_job.name from the previous step
job_name = "batches/5crm0h0t2580p641oyxpdhpku0q5h9o8ahzp"  # (e.g. 'batches/your-batch-id')
batch_job = client.batches.get(name=job_name)

completed_states = set([
    'JOB_STATE_SUCCEEDED',
    'JOB_STATE_FAILED',
    'JOB_STATE_CANCELLED',
    'JOB_STATE_EXPIRED',
])

print(f"Polling status for job: {job_name}")
batch_job = client.batches.get(name=job_name) # Initial get
while batch_job.state.name not in completed_states:
  print(f"Current state: {batch_job.state.name}")
  sleep(30) # Wait for 30 seconds before polling again
  batch_job = client.batches.get(name=job_name)

print(f"Job finished with state: {batch_job.state.name}")
if batch_job.state.name == 'JOB_STATE_FAILED':
    print(f"Error: {batch_job.error}")

Polling status for job: batches/5crm0h0t2580p641oyxpdhpku0q5h9o8ahzp
Current state: JOB_STATE_PENDING
Current state: JOB_STATE_RUNNING
Current state: JOB_STATE_RUNNING
Current state: JOB_STATE_RUNNING
Current state: JOB_STATE_RUNNING
Current state: JOB_STATE_RUNNING
Current state: JOB_STATE_RUNNING
Current state: JOB_STATE_RUNNING
Job finished with state: JOB_STATE_SUCCEEDED

In [19]:
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

# Use the name of the job you want to check
# e.g., inline_batch_job.name from the previous step
job_name = "batches/5crm0h0t2580p641oyxpdhpku0q5h9o8ahzp"
batch_job = client.batches.get(name=job_name)

outputs = {}
outputs_text = {}

if batch_job.state.name == 'JOB_STATE_SUCCEEDED':

    # If batch job was created with a file
    if batch_job.dest and batch_job.dest.file_name:
        # Results are in a file
        result_file_name = batch_job.dest.file_name
        print(f"Results are in file: {result_file_name}")

        print("Downloading result file content...")
        file_content = client.files.download(file=result_file_name)
        # Process file_content (bytes) as needed
        print(file_content.decode('utf-8'))

    # If batch job was created with inline request
    # (for embeddings, use batch_job.dest.inlined_embed_content_responses)
    elif batch_job.dest and batch_job.dest.inlined_responses:
        # Results are inline
        print("Results are inline:")
        for i, inline_response in enumerate(batch_job.dest.inlined_responses):
            if inline_response.response:
                # Accessing response, structure may vary.
                try:
                    outputs_text[i] = literal_eval(inline_response.response.text)
                except AttributeError as e:
                    print(f"AttributeError in Response {i+1}: {e}")
                    outputs[i] = inline_response.response  # Fallback
            elif inline_response.error:
                print(f"Error: {inline_response.error}")
    else:
        print("No results found (neither file nor inline).")
else:
    print(f"Job did not succeed. Final state: {batch_job.state.name}")
    if batch_job.error:
        print(f"Error: {batch_job.error}")

Results are inline:

In [20]:
with open(f'temp/translation_output/eng/{dataset_folder}/{os.path.basename(dataset_path)}', 'w') as f:
	json.dump(outputs_text, f, indent=4, ensure_ascii=False)

## Preprocess

In [21]:
with open(f'temp/translation_output/eng/{dataset_folder}/{os.path.basename(dataset_path)}', 'r') as f:
	outputs_text = json.load(f)

In [22]:
def add_space_around_punctuation(text):
    # Except for '-'
    # Ensure space before punctuation
    text = re.sub(r'(\S)([.,!?\(\)\"\';:+/]+)', r'\1 \2', text)
    # Ensure space after punctuation
    text = re.sub(r'([.,!?\(\)\"\';:+/]+)(\S)', r'\1 \2', text)
    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)
    # Ensure punctuation sequences like '...' are split into spaced dots
    text = re.sub(r'([.]{2,})', lambda m: ' '.join(m.group(1)), text)
    return text.strip()

In [23]:
mismatch_indexes = []
mismatch_notes = {}
for key, instance in outputs_text.items():
	translated_text = add_space_around_punctuation(instance['translated_text'].lower()).strip()
	mismatched = False
	for triplet in instance['translated_triplets']:
		aspect_term = add_space_around_punctuation(triplet['aspect_term'].lower()).strip()
		opinion_term = add_space_around_punctuation(triplet['opinion_term'].lower()).strip()
		if aspect_term not in translated_text and aspect_term != 'null':
			print(f"Mismatch in instance {key}: aspect_term '{aspect_term}' not found in {translated_text}")
			mismatch_notes[key] = mismatch_notes.get(key, []) + [f"aspect_term '{aspect_term}' not found"]
			mismatched = True
		if opinion_term not in translated_text and opinion_term != 'null':
			print(f"Mismatch in instance {key}: opinion_term '{opinion_term}' not found in {translated_text}")
			mismatch_notes[key] = mismatch_notes.get(key, []) + [f"opinion_term '{opinion_term}' not found"]
			mismatched = True
	if mismatched:
		mismatch_indexes.append(key)
print(f"Total mismatches found: {len(mismatch_indexes)}")

Mismatch in instance 24: opinion_term 'not cold enough in room 515' not found in the ac in room 515 is not cold enough .
Mismatch in instance 96: opinion_term 'not available' not found in there were no sandals . they said there was free wifi , but it turned out they didn ' t give the password , which is strange .
Mismatch in instance 106: opinion_term 'already complained but there was no solution' not found in the hot water in the bathroom was not working . we already complained , but there was no solution . we had to bathe in the evening and morning with cold water .
Mismatch in instance 109: opinion_term 'from the outside , it doesn ' t look like a hotel . more like a boarding house .' not found in the pillows are hard and thick . the curtains cannot be closed tightly . there is no hot water . the faucet is broken . there is no sink . the blanket is small . from the outside , it doesn ' t look like a hotel ; it ' s more like a boarding house . the reception area is messy . if a room is like this , the price should be at least 120k . thank you .
Mismatch in instance 119: opinion_term 'already reported , but it wasn ' t fixed' not found in the wifi is bad . i already reported it , but it wasn ' t fixed .
Mismatch in instance 141: opinion_term 'not provided' not found in the bathroom floor is slippery , no shower cap is provided , the bathroom door handle is heavy / difficult to turn , making me worried it couldn ' t be opened / might get locked from the inside . it would be better if a qibla direction indicator was provided in the room .
Mismatch in instance 142: opinion_term 'wasn ' t working and we had to wait again' not found in the receptionist had just woken up . the service was unfriendly . even upon arrival , the room wasn ' t ready , despite it being long past check-in time . then the ac wasn ' t working , and we had to wait again . the check-out process was also disappointing . i don ' t want to stay at this hotel again .
Mismatch in instance 167: aspect_term 'pouch containing toiletries' not found in we chose a room with a bed that fits 2 people . initially , it was good , but in the middle of the night , the electricity ran out , and we were told to move to a smaller room with a smaller bed . there was no pouch provided containing toiletries . quite disappointed , actually .
Mismatch in instance 180: opinion_term 'tiring to climb stairs' not found in it ' s decent . even though climbing stairs is tiring , it ' s great .
Mismatch in instance 186: opinion_term 'provide it daily to hotel guests' not found in please provide aqua drinking water daily to hotel guests . thank you .
Mismatch in instance 203: opinion_term 'only one was provided' not found in the room was good and comfortable , but unfortunately , only one towel was provided .
Mismatch in instance 214: opinion_term 'not available even though we stayed for 4 consecutive days' not found in there were no snacks available even though we stayed for 4 consecutive days .
Mismatch in instance 250: opinion_term 'constantly running , making it difficult to sleep' not found in when i got a room with constantly running water , it made it difficult to sleep . the food was good , thankfully , and the location is strategic . the corridor leading to the room was musty ; changing or removing the carpet would probably be better . the staff ? hmm .
Mismatch in instance 268: opinion_term 'hopefully better after renovation' not found in the room is spacious , the ac is cold , and it ' s clean . the toilet is old , and there is no water heater . hopefully , it will be better after renovation .
Mismatch in instance 291: opinion_term 'aren ' t here' not found in the bedroom and bathroom were comfortable , clean , and spacious . however , when i arrived , the pillowcases hadn ' t been put on yet . as i recall , in the airy rooms where i ' ve stayed before , snacks and toiletries from airy were always provided , so why aren ' t they here ?
Mismatch in instance 291: opinion_term 'aren ' t here' not found in the bedroom and bathroom were comfortable , clean , and spacious . however , when i arrived , the pillowcases hadn ' t been put on yet . as i recall , in the airy rooms where i ' ve stayed before , snacks and toiletries from airy were always provided , so why aren ' t they here ?
Mismatch in instance 293: opinion_term 'not provided' not found in no drinks were provided , only one set of toiletries , the stairs are small and very winding , not child-friendly . we ordered a double bed but were given a twin .
Mismatch in instance 316: opinion_term 'hopefully it will be better' not found in give double towels , the ac is not cold enough . hopefully , it will be better .
Mismatch in instance 328: opinion_term 'not available' not found in the bathroom door was broken . there was no blanket . it was poorly prepared for guests .
Mismatch in instance 330: opinion_term 'only one bottle of water for two days' not found in the tv uses an indoor antenna , so the reception is unclear . only one bottle of water was provided for two days . the room dividers are made of plywood .
Mismatch in instance 336: opinion_term 'the wi-fi on the 2nd floor needs to be fixed , it often disconnects' not found in the wi-fi on the 2nd floor needs to be fixed ; it often disconnects . it also frequently lags when playing mobile legends .
Mismatch in instance 418: opinion_term 'not hot enough' not found in the service was friendly , the room was cold , but the shower water wasn ' t hot enough .
Mismatch in instance 439: opinion_term 'missing a thermos , a kettle for boiling hot water' not found in this is great , very comfortable . what ' s missing is a thermos , a kettle for boiling hot water , tea sachets , and sugar so one could make tea in the morning . but it ' s already good .
Mismatch in instance 483: aspect_term 'picture quality of the tv channels' not found in the tv channels need improvement ; their picture quality is poor . it would be better to just use cable tv , if possible .
Mismatch in instance 505: opinion_term 'bad signal' not found in the room was spacious and tidy , but unfortunately , the tv signal happened to be bad , and a request to change to another room with a good signal was not allowed because the booking was from airy rooms , and wi-fi was not available .
Mismatch in instance 523: opinion_term 'already occupied and messy when i tried to enter' not found in the service was poor due to a receptionist ' s mistake . when i tried to enter my room , it was already occupied and messy .
Mismatch in instance 540: opinion_term 'was immediately rejected due to miscommunication between airy and the owner of the place' not found in upon arrival , we were immediately rejected due to miscommunication between airy and the owner of the place . the tv was broken , and the curtains were not fully closed . the room was very spacious , but the water was not hot enough . the bed was very comfortable . there was also a table and chair for working , and there was a refrigerator for storing food and drinks .
Mismatch in instance 577: opinion_term 'no room' not found in it ' s not like proper accommodation . we had already confirmed , but there wasn ' t even a room . it was just a waste of money .
Mismatch in instance 580: opinion_term 'only one set is provided' not found in the bathroom sink is often clogged . only one set of toiletries is provided . for room cleaning , it ' s only tidied up , and the bedcover isn ' t replaced .
Mismatch in instance 606: opinion_term 'not tasty' not found in the room was clean , the toilet was clean , the ac was cold , and the hot water ran smoothly . there were quite a lot of mosquitoes , which should be noted . during breakfast , we were not informed that the food was already cold , so it wasn ' t tasty .
Mismatch in instance 624: opinion_term 'not enough electrical outlets for phones' not found in there aren ' t enough electrical outlets for phones in the room . thank you .
Mismatch in instance 627: opinion_term 'will be a regular' not found in it ' s very clean , the bathroom is clean , there ' s a bed , tv , and snacks available . i ' m very happy to stay here and will definitely be a regular .
Mismatch in instance 679: opinion_term 'can leave luggage in the lobby' not found in a good and unique accommodation , clean inside . the food is delicious , and the service is very satisfying . you can leave your luggage in the lobby .
Mismatch in instance 685: opinion_term 'hopefully it can be improved' not found in it ' s comfortable , but the ac is not cold enough . hopefully , it can be improved . thank you .
Mismatch in instance 693: opinion_term 'no options' not found in unfortunately , there were no smoking room options , and no breakfast options were available , though the provided breakfast was okay .
Mismatch in instance 753: opinion_term 'near eka hospital , ocean park' not found in the room is very comfortable , clean , the ac is good , parking is good , the receptionist is good , and the location is strategic , near eka hospital and ocean park .
Mismatch in instance 759: opinion_term 'poor coverage' not found in the hotel is good , the food is sufficient , and the wifi coverage is poor .
Mismatch in instance 769: opinion_term 'a lot of hair stuck to it' not found in the room smelled of cigarette smoke . there was a lot of hair stuck to the blanket . the hot water wasn ' t working .
Mismatch in instance 794: opinion_term 'unfortunately the hotel is undergoing renovation' not found in the location is good , suitable for those who want to shop at the factory outlets . unfortunately , the hotel is undergoing renovation , so the atmosphere is less pleasant .
Mismatch in instance 796: aspect_term 'overall everything' not found in overall , everything was good , except for the cleanliness of the bed .
Mismatch in instance 841: opinion_term 'grew mold' not found in the furniture is good , but unfortunately , the elevator is not yet operational . the room is not very clean ; mold even grew in the bathroom . but overall , it ' s quite decent for that price .
Mismatch in instance 843: opinion_term 'poor signal' not found in everything is good , only the signal is poor .
Mismatch in instance 862: opinion_term 'many were dead' not found in the cleanliness of the room ' s terrace was a bit dirty and dusty , and many of the room ' s interior lights were dead .
Mismatch in instance 895: opinion_term 'many mosquitoes , spiderwebs on the ceiling' not found in the ac is not cold enough . the lighting is poor because there are only 2 lights in the room and they are dim . there are many mosquitoes and spiderwebs on the ceiling of the room and toilet . the towels are dirty and have rust stains . the room and toilet smell musty . there is no pleasant scent whatsoever in the room . well , it ' s consistent with the price .
Mismatch in instance 929: opinion_term 'even though it was still 2 hours before check-in time , we were allowed to enter the room' not found in it was good and satisfying ; we were allowed to enter the room even though it was still 2 hours before check-in time . however , when we just entered the room , the toilet ( closed ) was still dirty , and the mat in front of the toilet was also dirty .
Mismatch in instance 960: aspect_term 'check-in' not found in there were no towels , the room was moldy , there was an unpleasant smell , and the bedsheets were also not clean . as a result , as soon as we checked in , we immediately went to find another airy .
Mismatch in instance 966: aspect_term 'ac remote' not found in however , the water often stops , that ' s the only issue . besides that , the ac and tv remotes are missing .
Mismatch in instance 979: opinion_term 'comfortable for a year-end holiday' not found in a comfortable place for a year-end holiday , with attractive options offered by airy and friendly service .
Total mismatches found: 47

In [24]:
mismatch_indexes = list(set(mismatch_indexes))
len(mismatch_indexes)

47

In [25]:
input_eng = []
for key, instance in outputs_text.items():
	translated_text = add_space_around_punctuation(instance['translated_text'].lower()).strip()
	input_eng.append(f'{translated_text} [A] [O] [S]')

target_eng = []
for key, instance in outputs_text.items():
	triplet_texts = []
	for triplet in instance['translated_triplets']:
		aspect_term = add_space_around_punctuation(triplet['aspect_term'].lower()).strip()
		opinion_term = add_space_around_punctuation(triplet['opinion_term'].lower()).strip()
		sentiment = triplet['sentiment_polarity'].lower().strip()
		triplet_texts.append(f"[A] {aspect_term} [O] {opinion_term} [S] {sentiment}")
	target_eng.append(' [SSEP] '.join(triplet_texts))
print(len(input_eng), len(target_eng))

1000 1000

In [26]:
df_dataset['input_eng'] = input_eng
df_dataset['target_eng'] = target_eng
df_dataset['aspect_or_opinion_not_in_input'] = [str(idx) in mismatch_indexes for idx in df_dataset.index]
df_dataset['mismatch_notes'] = [mismatch_notes.get(str(idx), []) for idx in df_dataset.index]
df_dataset['mismatch_notes_format'] = df_dataset['mismatch_notes'].apply(lambda x: '\n'.join(x))

In [27]:
df_dataset['target_format'] = df_dataset['target'].apply(lambda x: '\n'.join(x.split(' [SSEP] ')))
df_dataset['target_format_eng'] = df_dataset['target_eng'].apply(lambda x: '\n'.join(x.split(' [SSEP] ')))

In [28]:
df_dataset

,sentence_id,instance_id,task_elements,input,target,element_order,input_eng,target_eng,aspect_or_opinion_not_in_input,mismatch_notes,mismatch_notes_format,target_format,target_format_eng
0,3500,17500,aos,pelayanan nya sangat ramah . [A] [O] [S],[A] pelayanan nya [O] sangat ramah [S] positive,aos,the service is very friendly . [A] [O] [S],[A] service [O] very friendly [S] positive,False,[],,[A] pelayanan nya [O] sangat ramah [S] positive,[A] service [O] very friendly [S] positive
1,3501,17505,aos,sayang wifi tidak bagus harus keluar kamar . [...,[A] wifi [O] tidak bagus harus keluar kamar [S...,aos,"unfortunately , the wi-fi is not good ; you ha...",[A] wi-fi [O] not good ; you have to go out of...,False,[],,[A] wifi [O] tidak bagus harus keluar kamar [S...,[A] wi-fi [O] not good ; you have to go out of...
2,3502,17510,aos,"tulisannya twin bed , tetapi yang ada kamarnya...",[A] kamarnya [O] beda [S] negative,aos,"it said twin bed , but the room provided was d...",[A] room [O] different [S] negative,False,[],,[A] kamarnya [O] beda [S] negative,[A] room [O] different [S] negative
3,3503,17515,aos,"over all baik , hanya sja akan lebih memuaskan...",[A] over all [O] baik [S] positive [SSEP] [A] ...,aos,"overall good , it would just be more satisfyin...",[A] overall [O] good [S] positive [SSEP] [A] h...,False,[],,[A] over all [O] baik [S] positive\n[A] air ho...,[A] overall [O] good [S] positive\n[A] hot wat...
4,3504,17520,aos,fasilatas sesuia . [A] [O] [S],[A] fasilitas [O] sesuai [S] positive,aos,the facilities are appropriate . [A] [O] [S],[A] facilities [O] appropriate [S] positive,False,[],,[A] fasilitas [O] sesuai [S] positive,[A] facilities [O] appropriate [S] positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4495,22475,aos,"lumayan , harga murah banged . [A] [O] [S]",[A] harga [O] murah banget [S] positive [SSEP]...,aos,"it ' s decent , the price is very cheap . [A] ...",[A] price [O] very cheap [S] positive [SSEP] [...,False,[],,[A] harga [O] murah banget [S] positive\n[A] n...,[A] price [O] very cheap [S] positive\n[A] nul...
996,4496,22480,aos,buat lakilaki dan perempuan yang belum menikah...,[A] null [O] buat laki laki dan perempuan yang...,aos,unmarried men and women are also allowed to sh...,[A] null [O] unmarried men and women are also ...,False,[],,[A] null [O] buat laki laki dan perempuan yang...,[A] null [O] unmarried men and women are also ...
997,4497,22485,aos,"kamar sangat nyaman dan bersih , sungguh menye...",[A] kamar [O] sangat nyaman [S] positive [SSEP...,aos,"the room is very comfortable and clean , truly...",[A] room [O] very comfortable [S] positive [SS...,False,[],,[A] kamar [O] sangat nyaman [S] positive\n[A] ...,[A] room [O] very comfortable [S] positive\n[A...
998,4498,22490,aos,"kamarnya luas , kasurnya empuk , kamar mandiny...",[A] kamarnya [O] luas [S] positive [SSEP] [A] ...,aos,"the room is spacious , the bed is soft , and t...",[A] room [O] spacious [S] positive [SSEP] [A] ...,False,[],,[A] kamarnya [O] luas [S] positive\n[A] kasurn...,[A] room [O] spacious [S] positive\n[A] bed [O...
999,4499,22495,aos,"kamar tidak sesuai , tempat parkir kurang nyam...",[A] kamar [O] tidak sesuai [S] negative [SSEP]...,aos,"the room was not as expected , the parking was...",[A] room [O] not as expected [S] negative [SSE...,False,[],,[A] kamar [O] tidak sesuai [S] negative\n[A] t...,[A] room [O] not as expected [S] negative\n[A]...

In [29]:
df_dataset[['sentence_id', 'input', 'input_eng', 'target_format', 'target_format_eng', 'aspect_or_opinion_not_in_input', 'mismatch_notes_format']].rename({'target_format': 'target', 'target_format_eng': 'target_eng', 'mismatch_notes_format': 'mismatch_notes'}).to_csv(f'temp/translation_output/eng/{dataset_folder}/translated_dataset_{lang}_{split}.csv', index=False)